import { GoogleGenAI } from "@google/genai";
import { readData, writeData } from "@/lib/storage";
import type { Concept } from "@/types";

/** Load saved concepts */
async function loadConcepts(): Promise<Concept[]> {
  return (await readData<Concept[]>("concepts.json")) ?? [];
}

/** Save concepts */
async function saveConcepts(concepts: Concept[]) {
  await writeData("concepts.json", concepts);
}

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY ?? "",
});

/**
 * POST /api/explain
 * Takes { input: string } — a term, headline, tweet, or short post.
 * Returns a full Concept object generated by Gemini.
 */
export async function POST(request: Request) {
  const { input } = (await request.json()) as { input: string };

  if (!input || input.trim().length === 0) {
    return Response.json({ error: "Input is required" }, { status: 400 });
  }

  // Check cache first — if we already have this concept, return it
  const cached = await loadConcepts();
  const inputLower = input.trim().toLowerCase();
  const inputSlug = inputLower.replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const existing = cached.find((c) => {
    return c.name.toLowerCase() === inputLower || c.slug === inputSlug;
  });
  if (existing) {
    return Response.json(existing);
  }

  const prompt = `You are an AI educator. A user has pasted the following text — it could be a technical term, a headline, a tweet, or a short post about AI.

Analyse the input and respond with a JSON object (no markdown, no code fences, just raw JSON) matching this exact structure:

{
  "name": "The core concept name (e.g. 'Retrieval-Augmented Generation')",
  "simpleExplanation": "A plain-language explanation in 2-3 sentences. Imagine explaining to a smart friend who doesn't work in tech.",
  "deeperExplanation": "A more detailed, technical explanation in 3-5 sentences. Include how it works and why it's designed that way.",
  "whyItMattersNow": "2-3 sentences on why this concept is relevant right now in the AI landscape.",
  "relatedConcepts": ["concept1", "concept2", "concept3"],
  "examples": ["A concrete example", "Another example", "A third example"],
  "resources": [
    { "title": "Resource name", "url": "https://example.com" },
    { "title": "Another resource", "url": "https://example.com" }
  ]
}

Rules:
- relatedConcepts should be 3-5 short concept names (not descriptions)
- examples should be 2-3 real, concrete examples
- resources should be 2-3 real, well-known resources (official docs, Wikipedia, influential blog posts)
- Keep explanations clear and specific, not generic
- Only return valid JSON, nothing else

User input: ${input}`;

  // Models to try in order — if one fails, try the next
  const models = ["gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.0-flash"];

  try {
    let text = "";
    let succeeded = false;

    for (const model of models) {
      try {
        console.log(`Trying ${model}...`);
        const response = await ai.models.generateContent({
          model,
          contents: prompt,
        });
        text = response.text?.trim() ?? "";
        succeeded = true;
        console.log(`Success with ${model}`);
        break;
      } catch (err: unknown) {
        const status = (err as { status?: number }).status;
        console.log(`${model} failed (${status}), trying next...`);
      }
    }

    if (!succeeded) {
      return Response.json(
        { error: "Gemini is temporarily overloaded. Please wait a minute and try again." },
        { status: 503 }
      );
    }

    // Parse the JSON response from Gemini
    const parsed = JSON.parse(text);

    // Build a slug from the concept name
    const slug = parsed.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");

    const concept: Concept = {
      id: `concept-${slug}`,
      name: parsed.name,
      slug,
      simpleExplanation: parsed.simpleExplanation,
      deeperExplanation: parsed.deeperExplanation,
      whyItMattersNow: parsed.whyItMattersNow,
      relatedConcepts: parsed.relatedConcepts ?? [],
      examples: parsed.examples ?? [],
      resources: parsed.resources ?? [],
    };

    // Save to cache
    const all = await loadConcepts();
    // Replace if same slug exists, otherwise add
    const idx = all.findIndex((c) => c.slug === concept.slug);
    if (idx >= 0) {
      all[idx] = concept;
    } else {
      all.push(concept);
    }
    await saveConcepts(all);

    return Response.json(concept);
  } catch (error: unknown) {
    console.error("Explain API error:", error);
    const status = (error as { status?: number }).status;
    if (status === 429 || status === 503) {
      return Response.json(
        { error: "Gemini is temporarily overloaded. Please wait a minute and try again." },
        { status: 503 }
      );
    }
    return Response.json(
      { error: "Failed to generate explanation. Please try again." },
      { status: 500 }
    );
  }
}
